console.log('hello')
let b = localStorage.getItem('array')
console.log(b)
let obj = localStorage.getItem('objStore')
obj = JSON.parse(obj)
console.log(obj)
let arr = localStorage.getItem('arrayStore')
arr = JSON.parse(arr)
console.log(arr)